const CURRENT_DIRECTORY = __dirname;
const MAX_BOOK = 1000;
const MAX_CUSTOMER = 1000;
const MAX_ORDER = 1000;
const MAX_AUTHOR = 1000;
const MAX_CONTAINS_ORDER_BOOK = 200;
const MAX_BELONGS_BOOK_AUTHOR = 200;

module.exports = {
    CURRENT_DIRECTORY,
    MAX_BOOK,
    MAX_CUSTOMER,
    MAX_ORDER,
    MAX_AUTHOR,
    MAX_CONTAINS_ORDER_BOOK,
    MAX_BELONGS_BOOK_AUTHOR
}